version: "3.8"

services:

  gitlab:
    image: "gitlab/gitlab-ce:8.15.2-ce.0"
    restart: "always"
    hostname: "gitlab"
    ports:
      - "8080:80"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://gitlab"

  jenkins:
    build: ./jenkins
    restart: "always"
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-certs:/certs/client:ro

  artifactory:
      image: docker.bintray.io/jfrog/artifactory-oss:6.23.3
      ports:
        - 8082:8081
      volumes:
        - artifactory-data:/var/opt/jfrog/artifactory
      restart: always

  sonarqube:
    image: sonarqube:8-community
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    ports:
      - "8083:9000"

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:

  gitlab-config:
  gitlab-logs:
  gitlab-data:
  jenkins-data:
  jenkins-certs:
  artifactory-data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  postgresql:
  postgresql_data:
