version: "3.8"

services:

  nginx:
    image: 'nginx:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './nginx/config:/etc/nginx'
      - './nginx/cert:/etc/cert:ro'
    extra_hosts:
      gitlab.jmpesp.local: 172.27.48.1
      jenkins.jmpesp.local: 172.27.48.1
      sonar.jmpesp.local: 172.27.48.1
      artifactory.jmpesp.local: 172.27.48.1
    restart: always

  gitlab:
    image: "gitlab/gitlab-ce:latest"
    restart: "always"
    ports:
      - '22:22'
      - "8888:80"
    volumes:
      - ./gitlab/config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://gitlab.jmpesp.local"
        letsencrypt['enabled'] = false
        nginx['enable'] = true
        nginx['redirect_http_to_https'] = false
    extra_hosts:
      gitlab.jmpesp.local: 172.27.48.1
      jenkins.jmpesp.local: 172.27.48.1
      sonar.jmpesp.local: 172.27.48.1
      artifactory.jmpesp.local: 172.27.48.1

  jenkins:
    build: ./jenkins
    restart: "always"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-certs:/certs/client:ro
      - ./jenkins/config:/etc/jenkins/config
    environment:
      CASC_JENKINS_CONFIG: /etc/jenkins/config/jenkins.yml
    extra_hosts:
      gitlab.jmpesp.local: 172.27.48.1
      jenkins.jmpesp.local: 172.27.48.1
      sonar.jmpesp.local: 172.27.48.1
      artifactory.jmpesp.local: 172.27.48.1

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    restart: always
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - artifactory-data:/var/opt/jfrog/artifactory
    extra_hosts:
      gitlab.jmpesp.local: 172.27.48.1
      jenkins.jmpesp.local: 172.27.48.1
      sonar.jmpesp.local: 172.27.48.1
      artifactory.jmpesp.local: 172.27.48.1

  sonarqube:
    image: sonarqube:latest
    restart: "always"
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    ports:
      - "9000:9000"
    ulimits:
      nofile:
          soft: 262144
          hard: 262144
    extra_hosts:
      gitlab.jmpesp.local: 172.27.48.1
      jenkins.jmpesp.local: 172.27.48.1
      sonar.jmpesp.local: 172.27.48.1
      artifactory.jmpesp.local: 172.27.48.1

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    extra_hosts:
      gitlab.jmpesp.local: 172.27.48.1
      jenkins.jmpesp.local: 172.27.48.1
      sonar.jmpesp.local: 172.27.48.1
      artifactory.jmpesp.local: 172.27.48.1

volumes:

  gitlab-config:
  gitlab-logs:
  gitlab-data:
  jenkins-data:
  jenkins-certs:
  artifactory-data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  postgresql:
  postgresql_data:
