apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: jenkins-certs
  name: jenkins-certs
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi