apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: nginx
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: ""
        name: nginx
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
        volumeMounts:
        - mountPath: /etc/nginx
          name: nginx-config
          readOnly: true
        - mountPath: /etc/cert
          name: nginx-certs
          readOnly: true
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: nginx-config
        persistentVolumeClaim:
          claimName: nginx-config
          readOnly: true
      - name: nginx-certs
        persistentVolumeClaim:
          claimName: nginx-certs
          readOnly: true
