---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-config-volume
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /run/desktop/mnt/host/c/Users/robjb/Documents/git/DevOpsInf/nginx/config
    type: Directory
  claimRef:
     namespace: default
     name: nginx-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-config
spec:
  storageClassName: standard
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
