apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller-admission
  namespace: kube-system
  labels:
      addonmanager.kubernetes.io/mode: Reconcile
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/name: ingress-nginx
spec:
  type: LoadBalancer
  ports:
    - name: https-webhook
      port: 443
      protocol: TCP
      targetPort: webhook
    - name: proxied-tcp-22-gitlab
      port: 22
      targetPort: 22
      nodePort: 30000 # Only helps with Minikube as LoadBalancer gets a NodePort so specify a static port
      protocol: TCP
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
