apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: gitlab-config
  name: gitlab-config
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
