apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: gitlab-data
  name: gitlab-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10G
