apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: gitlab-logs
  name: gitlab-logs
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1G
