apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: db
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: secrets
              key: POSTGRES_USER
        image: postgres:latest
        imagePullPolicy: ""
        name: db
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: postgresql
        - mountPath: /var/lib/postgresql/data
          name: postgresql-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: postgresql
        persistentVolumeClaim:
          claimName: postgresql
      - name: postgresql-data
        persistentVolumeClaim:
          claimName: postgresql-data
