credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          description: "Deploy creds"
          id: "Artifactory"
          password: "${ARTIFACTORY_PASSWORD}"
          scope: GLOBAL
          username: "${ARTIFACTORY_USERNAME}"
      - usernamePassword:
          id: "Gitlab creds"
          password: "${GITLAB_PASSWORD}"
          scope: GLOBAL
          username: "${GITLAB_USERNAME}"
      - string:
          id: "Sonar"
          scope: GLOBAL
          secret: "${SONAR_TOKEN}"
jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  labelAtoms:
  - name: "Windows"
  - name: "WindowsHost"
  - name: "master"
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  noUsageStatistics: true
  nodes:
  - permanent:
      labelString: "Windows"
      launcher:
        jnlp:
          webSocket: true
          workDirSettings:
            disabled: false
            failIfWorkDirIsMissing: false
            internalDir: "remoting"
      mode: EXCLUSIVE
      name: "WindowsHost"
      remoteFS: "C:\\cicd\\jenkins\\agent"
      retentionStrategy: "always"
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "admin"
        name: "admin"
        properties:
        - "slack"
        - "theme"
        - "apiToken"
        - favoriting:
            autofavoriteEnabled: true
        - "favorite"
        - preferredProvider:
            providerId: "default"
        - "timezone"
        - mailer:
            emailAddress: "admin@jmpesp.local"
  slaveAgentPort: 50000
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - list:
      columns:
      - "status"
      - "weather"
      - "jobName"
      - "lastSuccess"
      - "lastFailure"
      - "lastDuration"
      - "buildButton"
      - "builtOnColumn"
      - "favoriteColumn"
      jobNames:
      - "PoshC2"
      name: "C2Frameworks"
  - list:
      columns:
      - "status"
      - "weather"
      - "jobName"
      - "lastSuccess"
      - "lastFailure"
      - "lastDuration"
      - "buildButton"
      - "builtOnColumn"
      - "favoriteColumn"
      jobNames:
      - "PowerShellMacro"
      name: "Execution"
  - list:
      columns:
      - "status"
      - "weather"
      - "jobName"
      - "lastSuccess"
      - "lastFailure"
      - "lastDuration"
      - "buildButton"
      - "builtOnColumn"
      - "favoriteColumn"
      jobNames:
      - "SafetyDump"
      - "Seatbelt"
      name: "Modules"
  - all:
      name: "all"
  viewsTabBar: "standard"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  sSHD:
    port: -1
  scriptApproval:
    approvedSignatures:
    - "new java.io.File java.lang.String"
    - "staticMethod java.lang.System getenv java.lang.String"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods eachDirRecurse\
      \ java.io.File groovy.lang.Closure"
unclassified:
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
  buildStepOperation:
    enabled: false
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
  gitHubPluginConfig:
    hookUrl: "https://jenkins.jmpesp.local/github-webhook/"
  gitSCM:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  ivyBuildTrigger:
    extendedVersionMatching: false
  junitTestResultStorage:
    storage: "file"
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
    url: "https://jenkins.jmpesp.local/"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  mavenModuleSet:
    localRepository: "default"
  pollSCM:
    pollingThreadCount: 10
  slackNotifier:
    botUser: false
    sendAsText: false
  sonarGlobalConfiguration:
    buildWrapperEnabled: true
    installations:
    - credentialsId: "Sonar"
      name: "Sonarqube"
      serverUrl: "https://sonar.jmpesp.local"
      triggers:
        skipScmCause: false
        skipUpstreamCause: false
  themeManager:
    disableUserThemes: false
    theme: "material-indigo"
  timestamper:
    allPipelines: false
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
  msBuildSQRunnerInstallation:
    installations:
    - home: "C:\\tools\\sonar-scanner-msbuild\\"
      name: "SonarScannerMSBuild"
  msbuild:
    installations:
    - home: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\\
        Current\\Bin\\MSBuild.exe"
      name: "MSBuild"
