credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          description: "Deploy creds"
          id: "Artifactory"
          password: "{AQAAABAAAABQH763jmv73IKtFc0+PzYyn+Sz5wF7LNBssmEoth14Hr2Hpa//doO8qWuHp9HQnRNdafagAfTC2wsR/2Rxe2QXEidNp9AjciE7W13lg8ynUFa7O/ggC2/HzmH8QJ0NYOSI}"
          scope: GLOBAL
          username: "admin"
      - gitLabApiTokenImpl:
          apiToken: "{AQAAABAAAABQrz48lggPWQG6S39Q0L+xzU/PQ0gs5VdfvWSSADKP2R3ngiB7wrrR6YX+SpNloQEi3zUKreCAAtjdSUhRpT741lsjzPtPA89Jjr7OqHLpOIZ2MXr3RhywFd80K5Hurwub}"
          id: "GitLab"
          scope: GLOBAL
      - gitLabApiTokenImpl:
          apiToken: "{AQAAABAAAABQdCLA6KG93gwTdozWZzoq4F30/eGawzXjOTPG9S6dwK9jnFMeeoBzCj9G/mva2KfVb73eaeXIiW33q1SfQ5bWnNdnlO+q/lgq7dcw1pv2fe0zJRGd6z0GFxZf8zqr3HjG}"
          id: "Gitlab2"
          scope: GLOBAL
      - usernamePassword:
          id: "Gitlab creds"
          password: "{AQAAABAAAABQe70N+7FsoYA2gZfYvy4rOFvuFiJPIyrVP3cI+oVYL6954i/FohDq8UfVU78lf3Aa1NOtInGsxHz1hVgtFY7hsvZ9TANGhpGDgaGJKxnahC4+4SEWdLj0GvzyEqX6HdUN}"
          scope: GLOBAL
          username: "root"
      - string:
          id: "Sonar"
          scope: GLOBAL
          secret: "{AQAAABAAAABw+uqWkbL/QQaPn9Jdah4i53jsXx+goftzdCo9xtOpkICcEzUWORM26ZG58oxRzgsyeFBkNDBvwFnjN3xLLjO5XrzYMXcJ5vkIQvwhjkvNoqkDfpdhDmnBm+46eYtP768XAnw7RT8Nsoo0BzkWyGuyZZ0LUCrSXxuqbhcElMBPHnU=}"
jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  labelAtoms:
  - name: "Windows"
  - name: "WindowsHost"
  - name: "master"
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  noUsageStatistics: true
  nodes:
  - permanent:
      labelString: "Windows"
      launcher:
        jnlp:
          workDirSettings:
            disabled: false
            failIfWorkDirIsMissing: false
            internalDir: "remoting"
      mode: EXCLUSIVE
      name: "WindowsHost"
      remoteFS: "C:\\cicd\\jenkins\\agent"
      retentionStrategy: "always"
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "admin"
        name: "admin"
        properties:
        - "theme"
        - "apiToken"
        - favoriting:
            autofavoriteEnabled: true
        - "favorite"
        - preferredProvider:
            providerId: "default"
        - "timezone"
        - mailer:
            emailAddress: "admin@jmpesp.local"
  slaveAgentPort: 50000
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - list:
      columns:
      - "status"
      - "weather"
      - "jobName"
      - "lastSuccess"
      - "lastFailure"
      - "lastDuration"
      - "buildButton"
      - "builtOnColumn"
      - "favoriteColumn"
      jobNames:
      - "PoshC2"
      name: "C2Frameworks"
  - list:
      columns:
      - "status"
      - "weather"
      - "jobName"
      - "lastSuccess"
      - "lastFailure"
      - "lastDuration"
      - "buildButton"
      - "builtOnColumn"
      - "favoriteColumn"
      jobNames:
      - "PowerShellMacro"
      name: "Execution"
  - list:
      columns:
      - "status"
      - "weather"
      - "jobName"
      - "lastSuccess"
      - "lastFailure"
      - "lastDuration"
      - "buildButton"
      - "builtOnColumn"
      - "favoriteColumn"
      jobNames:
      - "SafetyDump"
      - "Seatbelt"
      name: "Modules"
  - all:
      name: "all"
  viewsTabBar: "standard"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  envInject:
    enableLoadingFromMaster: false
    enablePermissions: false
    hideInjectedVars: false
  sSHD:
    port: -1
  scriptApproval:
    approvedSignatures:
    - "new java.io.File java.lang.String"
    - "staticMethod java.lang.System getenv java.lang.String"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods eachDirRecurse\
      \ java.io.File groovy.lang.Closure"
unclassified:
  artifactoryBuilder:
    artifactoryServers:
    - artifactoryUrl: "http://artifactory.default.svc.cluster.local:8081/artifactory"
      bypassProxy: false
      connectionRetry: 3
      deployerCredentialsConfig:
        credentialsId: "Artifactory"
        overridingCredentials: false
        password: "{AQAAABAAAAAQty3sDbNO1fDUpAKf44mUlmray9rthyTuiLW0wEmvOKw=}"
        username: "****"
      deploymentThreads: 3
      serverId: "ARTIFACTORY"
      timeout: 300
    jfrogPipelinesServer:
      bypassProxy: false
      connectionRetries: 3
      credentialsConfig:
        ignoreCredentialPluginDisabled: true
        overridingCredentials: false
        password: "{AQAAABAAAAAQ0GzH4tQPmLat9q1wqLvn3vupSUc6tKmM5clL1PS/2YU=}"
        username: "****"
      timeout: 300
    useCredentialsPlugin: true
  bitbucketEndpointConfiguration:
    endpoints:
    - bitbucketCloudEndpoint:
        enableCache: false
        manageHooks: false
        repositoriesCacheDuration: 0
        teamCacheDuration: 0
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
  buildStepOperation:
    enabled: false
  email-ext:
    adminRequiredForTemplateTesting: false
    allowUnregisteredEnabled: false
    charset: "UTF-8"
    debugMode: false
    defaultBody: |-
      $PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:

      Check console output at $BUILD_URL to view the results.
    defaultContentType: "text/plain"
    defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
    defaultTriggerIds:
    - "hudson.plugins.emailext.plugins.trigger.FailureTrigger"
    mailAccount:
      smtpPassword: "{AQAAABAAAABAE0XJIBSkQKFtAdRI/mPjvsOuUOIZPQHOexHrD72B9+626+uCriCQNM4xMDMz0bYzPOwiXq26DVmeyT8yUwTiPmqq+H9BcKHOXePsuBLO8yI=}"
    maxAttachmentSize: -1
    maxAttachmentSizeMb: -1
    precedenceBulk: false
    watchingEnabled: false
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
  gitHubPluginConfig:
    hookUrl: "https://jenkins.jmpesp.local/github-webhook/"
  gitLabConnectionConfig:
    connections:
    - apiTokenId: "GitLab"
      clientBuilderId: "autodetect"
      connectionTimeout: 10
      ignoreCertificateErrors: true
      name: "Gitlab"
      readTimeout: 10
      url: "https://gitlab.jmpesp.local"
    - clientBuilderId: "autodetect"
      connectionTimeout: 10
      ignoreCertificateErrors: false
      readTimeout: 10
  gitSCM:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  ivyBuildTrigger:
    extendedVersionMatching: false
  junitTestResultStorage:
    storage: "file"
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
    url: "https://jenkins.jmpesp.local/"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  mavenModuleSet:
    localRepository: "default"
  pollSCM:
    pollingThreadCount: 10
  slackNotifier:
    botUser: false
    sendAsText: false
  sonarGlobalConfiguration:
    buildWrapperEnabled: true
    installations:
    - credentialsId: "Sonar"
      name: "Sonarqube"
      serverUrl: "http://sonar.jmpesp.local"
      triggers:
        skipScmCause: false
        skipUpstreamCause: false
  themeManager:
    disableUserThemes: false
    theme: "material-indigo"
  timestamper:
    allPipelines: false
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
  msBuildSQRunnerInstallation:
    installations:
    - home: "C:\\tools\\sonar-scanner-msbuild-5.0.4.24009-net46\\"
      name: "SonarScannerMSBuild"
  msbuild:
    installations:
    - home: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\MSBuild\\\
        Current\\Bin\\MSBuild.exe"
      name: "MSBuild"
